spring:
  application:
    name: hrportal
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

resend:
  email-templates:
    signup:
      name: ${RESEND_SIGNUPTEMPLATE_NAME}
      variables:
        - ${RESEND_SIGNUPTEMPLATE_ID_OTP}